version: '3.9'

volumes:
  gh-analyzer-db:
  gh-analyzer-redis:

services:
  db:
    image: postgres:15.1
    volumes:
      - gh-analyzer-db:/var/lib/postgresql/data
    env_file: .swarm/.env
  redis:
    image: redis:7.0.8
    volumes:
      - gh-analyzer-redis:/data
  app:
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    depends_on:
      - db
    env_file:
      - .swarm/.env
      - .swarm/.env.secrets
    stdin_open: true
    tty: true
  sidekiq:
    build: .
    volumes:
      - ./:/app
    entrypoint: bundle exec sidekiq
    depends_on:
      - redis
      - db
    env_file:
      - .swarm/.env
      - .swarm/.env.secrets
