version: '3.9'

services:
  db:
    image: postgres:15.1
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  web:
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    depends_on:
      - db
