version: '3.9'

services:
  db:
    image: postgres:15.1
    volumes:
      - db-tests:/var/lib/postgresql/data
    env_file: .swarm/.env
  app:
    ports:
      - 3000:3000
    image: ${IMAGE_NAME}
    env_file: .swarm/.env
    environment:
      - RAILS_ENV=test
    depends_on:
      - db

volumes:
  db-tests:
