version: '3.9'

volumes:
  gh-analyzer-db:

services:
  db:
    image: postgres:15.1
    volumes:
      - gh-analyzer-db:/var/lib/postgresql/data
    env_file: .swarm/.env
  app:
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    depends_on:
      - db
    env_file:
      - .swarm/.env
      - .swarm/.env.secrets
    stdin_open: true
    tty: true
