version: '3.9'

services:
  db:
    image: postgres:15.1
    volumes:
      - db-tests:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  web:
    image: ${IMAGE_NAME}
    depends_on:
      - db

volumes:
  db-tests:
