# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

describe Web::RepositoriesController do
  before do
    stub_request(:get, 'https://api.github.com/user/repos')
      .to_return(status: 200, body: gh_repositories, headers: {})
  end

  let(:gh_repositories) { YAML.load(Rails.root.join('spec/fixtures/files/github/repositories.yml').read) }

  # This should return the minimal set of attributes required to create a valid
  # Repository. As you add validations to Repository, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      get :index
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      get :show, params: { id: repositories(:repo_one) }
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get :new
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new Repository' do
        expect do
          post repositories_path, params: { repository: valid_attributes }
        end.to change(Repository, :count).by(1)
      end

      it 'redirects to the created repository' do
        post repositories_path, params: { repository: valid_attributes }
        expect(response).to redirect_to(repository_path(Repository.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Repository' do
        expect do
          post repositories_path, params: { repository: invalid_attributes }
        end.not_to change(Repository, :count)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post repositories_path, params: { repository: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested repository' do
      repository = Repository.create! valid_attributes
      expect do
        delete repository_path(repository)
      end.to change(Repository, :count).by(-1)
    end

    it 'redirects to the repositories list' do
      repository = Repository.create! valid_attributes
      delete repository_path(repository)
      expect(response).to redirect_to(repositories_path)
    end
  end
end
