default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV["POSTGRES_HOST"] %>
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  pool: <%= ENV.fetch('POSTGRES_POOL') { 5 } %>

development:
  <<: *default
  # database: github_analyzer_dev
  adapter: sqlite3
  database: db/test.sqlite3

test:
  <<: *default
  # database: github_analyzer_test
  adapter: sqlite3
  database: db/test.sqlite3

production:
  <<: *default
  database: github_analyzer_production
