default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV["POSTGRES_HOST"] %>
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  pool: <%= ENV.fetch('POSTGRES_POOL') { 5 } %>

development:
  <<: *default
  database: github_analyzer_dev

test:
  <<: *default
  database: github_analyzer_test

production:
  <<: *default
  database: github_analyzer_production
