version: '3.9'

services:
  nginx:
    image: nginx:1.23.3
    ports:
      - 80:80
  db:
    image: postgres:15.1
    volumes:
      - db-vol:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  web:
    image: inflame/github-analyzer:latest
    command: RAILS_ENV=production SECRET_KEY_BASE=1 bundle exec rails assets:precompile
    ports:
      - 3000:3000
    volumes:
      - ./public/assets:/app/public/assets:ro
      - ./log:/app/log:ro
    depends_on:
      - db
    environment:
      RAILS_ENV: production
      SECRET_KEY_BASE: test

volumes:
  db-vol:
