version: '3.9'

services:
  db:
    image: postgres:15.1
    volumes:
      - db-vol:/var/lib/postgresql/data
    env_file: .env
  app:
    depends_on:
      - db
    image: ${IMAGE_NAME}
    ports:
      - 3000:3000
    volumes:
      - ./public/assets:/app/public/assets
      - ./log:/app/log
      - ./repositories:/app/tmp/repositories
    env_file: .env
    healthcheck:
      test: ["CMD", "curl", "-i", "http://localhost:3000/healthcheck"]
    deploy:
      update_config:
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
  web:
    depends_on:
      - app
    image: ${NGINX_IMAGE_NAME}
    ports:
      - 80:80
    volumes:
      - ./public:/var/www/github-analyzer/public
      - ./log:/var/www/github-analyzer/log
    healthcheck:
      test: ["CMD", "service", "nginx", "status"]
    deploy:
      update_config:
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s


volumes:
  db-vol:
