name: ci

on:
  push:
    branches:
      - 'main'

env:
  IMAGE_NAME: ${{ secrets.DOCKER_HUB_USERNAME }}/${{secrets.DOCKER_HUB_IMAGE_NAME}}:${{github.sha}}
  IMAGE_NAME_LATEST: ${{ secrets.DOCKER_HUB_USERNAME }}/${{secrets.DOCKER_HUB_IMAGE_NAME}}:latest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: .
          file: .swarm/Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}
            ${{ env.IMAGE_NAME_LATEST }}
      # -
      #   name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v2
      # - uses: actions/checkout@master
      # -
      #   name: Build image
      #   run: docker buildx build -f .swarm/Dockerfile --build-arg BUILDKIT_INLINE_CACHE=1 -t ${IMAGE_NAME} -t ${IMAGE_NAME_LATEST} --cache-from ${IMAGE_NAME_LATEST} --push .
  test:
    needs: build
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run tests
        run: |
          docker compose -f docker-compose-tests.yml up -d
          # docker compose -f docker-compose-tests.yml exec web bundle exec rails db:create db:migrate
          docker compose -f docker-compose-tests.yml exec web bundle exec rspec
  deploy:
    needs: test
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: copy files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: ".swarm/docker-compose.yml"
          target: "~/github-analyzer-app/"
      - name: deploy application
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            docker stack deploy -c ~/github-analyzer-app/.swarm/docker-compose.yml github-analyzer
          
